### ISSUE TITLE
Atari 2600 and 7800

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#15]
```
We have emulators of both console on Wii but are dead. Wii2600 GUI its very 
annoying to use only with wiimote.

It could be great see a new emulator of Atari 2600 and 7800 :D
```

Original issue reported on code.google.com by `pmagnu...@gmail.com` on 21 Nov 2011 at 12:12

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
