### ISSUE TITLE
Zapper Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#17]
```
I want zapper Support, SuperScope Support, and Justifier Support for the SNES, 
NES, and Genesis with Nun-Chuck Support, because I want to play my old carts 
that don't work on Newer TVs unless I put them on the Wii and emulate them with 
a wii rifle I intend on buying or possibly given to me for Christmas... I've 
attached a file of what the rifle  looks like so you know it attaches to the 
wiimote no matter what.
```

Original issue reported on code.google.com by `radiofre...@gmail.com` on 11 Dec 2011 at 9:28

Attachments:
- [rifle 1.jpg](https://storage.googleapis.com/google-code-attachments/wii-mednafen/issue-17/comment-0/rifle 1.jpg)

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
