### ISSUE TITLE
Gamecube support?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#33]
```
Is there any chance of getting a version of this that runs on Gamecube?  Or a 
way that I could compile it for Gamecube myself?
```

Original issue reported on code.google.com by `dustin...@gmail.com` on 2 Mar 2012 at 4:14

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
