### ISSUE TITLE
SNES zip support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#38]
```
What steps will reproduce the problem?
1. Choose anygame.zip, containing anygame.smc
2. Press A
3. The game says "Unrecognized format. Sorry." 

What is the expected output? What do you see instead?
To load the game. All the other supported emulators work with the .zip 
extension. So much space is saved with zip compression if you have a lot of 
roms.

What version of the product are you using? On what operating system?
v0.1.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `Anonymou...@gmail.com` on 14 Apr 2012 at 9:06

**Comment by pfraktal** [comment]
I also have the same problem. I am using v0.1.1. any smc I load will not be recognized. I am on the wii. 4.3u

**Comment by bobbintb** [comment]
I'm pretty sure SNES isn't supported. It isn't listed in the list of supported systems.

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
