### ISSUE TITLE
Analog stick

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#43]
```
I have a classic controller pro, and although the analogs work outside of the 
emulator, when using mednafen, I can only navigate through menus and play with 
the D-pad!

```

Original issue reported on code.google.com by `gs.jug...@gmail.com` on 18 Jan 2013 at 9:20

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
