### ISSUE TITLE
Support for real PC Engine and PC-FX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#5]
```
I have few games for both systems, but don't have these consoles. Wanna play my 
real CDs with mednafen. Can you do it?

```

Original issue reported on code.google.com by `axelrag...@rambler.ru` on 14 Oct 2011 at 8:19

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
