### ISSUE TITLE
USB drive not mounting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#53]
```
What steps will reproduce the problem?
1. Opening the emulator through usb loader gx
2. Selecting to open a ROM from USB drive (which is fat32)
3.

What is the expected output? What do you see instead?
The expected output is for the emulator to recognize the drive and open my pace 
CD games. Instead it says it's unable to mount the drive

What version of the product are you using? On what operating system?
0.1.1 on wii

Please provide any additional information below.


```

Original issue reported on code.google.com by `machem...@gmail.com` on 25 Feb 2015 at 2:25

**Comment by raz0red** [comment]
Are you using the Wii or WiiU (via vWii)? I am seeing a similar message when I run within the WiiU, however, the drive appears to actually mount fine (if I select USB drive I can see the files). I will look into why it is displaying the message.

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
