### ISSUE TITLE
NTSC-filters, that simulates composide, s-video and rgb

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#6]
```
Could you do it? In my opinion, it would be good addon for 240i or 240p video 
modes.


```

Original issue reported on code.google.com by `axelrag...@rambler.ru` on 14 Oct 2011 at 9:05

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
