### ISSUE TITLE
Incompatibility with Wiiflow

### ISSUE THREAD

**Issue by Edu789** [raz0red/wii-mednafen#88]
When using any core through Wiiflow, when loading the game go to the wiimednafen menu, instead of starting the game...

**Comment by raz0red** [comment]
Quit a while ago, I made a number of updates to WiiMednanfen. One of the changes I made was compatibility with Wiiflow. 

However, I never officially released the updated version. I just did a quick build, you can download it here:

https://github.com/raz0red/wii-mednafen/suites/1001840003/artifacts/12972475

Please let me know if that resolved the Wiiflow issue.

Thanks,
Chris

**Comment by mrdeathjr28** [comment]
> Quit a while ago, I made a number of updates to WiiMednanfen. One of the changes I made was compatibility with Wiiflow.
> 
> However, I never officially released the updated version. I just did a quick build, you can download it here:
> 
> https://github.com/raz0red/wii-mednafen/suites/1001840003/artifacts/12972475
> 
> Please let me know if that resolves the Wiiflow issue.
> 
> Thanks,
> Chris

many thanks works very good and have new icon

**Comment by Edu789** [comment]
Now it is working as a plugin, the PC-FX is also working well, besides having many improvements...

**Comment by AdamCatalyst** [comment]
> > Quit a while ago, I made a number of updates to WiiMednanfen. One of the changes I made was compatibility with Wiiflow.
> > However, I never officially released the updated version. I just did a quick build, you can download it here:
> > https://github.com/raz0red/wii-mednafen/suites/1001840003/artifacts/12972475
> > Please let me know if that resolves the Wiiflow issue.
> > Thanks,
> > Chris
> 
> many thanks works very good and have new icon

Thank-you so much for this! Works much better for me than the 0.2pre version I'd been using.

**Comment by GhaleonX** [comment]
> Quit a while ago, I made a number of updates to WiiMednanfen. One of the changes I made was compatibility with Wiiflow.
> 
> However, I never officially released the updated version. I just did a quick build, you can download it here:
> 
> https://github.com/raz0red/wii-mednafen/suites/1001840003/artifacts/12972475
> 
> Please let me know if that resolves the Wiiflow issue.
> 
> Thanks, Chris

Sorry for my tardiness to this party, but is there any chance you could re-upload this? I was attempting the same thing as Edu789 xD

**EDIT** Nevermind, somebody sent it to me (and as it turns out I even already had it but wasn't aware haha)
