### ISSUE TITLE
Colorization for Older Gameboy games

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raz0red/wii-mednafen#9]
```
I was just wondering if it could be possible in a future release. Otherwise, 
this is a fantastic emulator, and has replaced several others already.
```

Original issue reported on code.google.com by `typewrit...@gmail.com` on 24 Oct 2011 at 5:38

**Comment by raz0red** [comment]
Closing old auto-imports from Google code. Please submit a GitHub issue if this still needs to be resolved.
Thanks!
